name: Software Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:          
  check-signedoff:
    runs-on: ubuntu-latest
    name: Check Signed Off
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Checking Sign off
        id: check-signoff
        run: php ./.github/scripts/check-signed-off.php github
  check-eof:
    runs-on: ubuntu-latest
    name: Check End of File
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Checking End of File
        id: check-eof
        run: php ./.github/scripts/check-eof-master.php ./